# Use a imagem oficial do Nginx
FROM nginx:stable-alpine-perl

ENV TZ=America/Fortaleza

WORKDIR /var/www/html/

# Copiar a configuração do Nginx personalizada
COPY --chown=nginx:nginx config/fastcgi.conf /etc/nginx/fastcgi.conf

COPY --chown=nginx:nginx fullstack/public/ /var/www/html/fullstack/src/public/